version: 0.2

phases:
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build

  post_build:
    commands:
      # copy the contents of /build to S3 bucket
      - aws s3 sync build s3://$contrax-web-landing-page/ --delete --exclude 'index.html' --acl public-read --cache-control 'max-age=860000'
      - aws s3 sync build s3://$contrax-web-landing-page/ --delete --exclude '*' --include 'index.html' --acl public-read --cache-control 'max-age=0'
      - aws cloudfront create-invalidation --distribution-id $E2BTE3X43IWKU7 --paths /*

artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: build